@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

InternshipDiary *-right-> "1" UniqueInternshipApplicationList
InternshipDiary *-right-> "1" UniqueStatusList
UniqueStatusList -[hidden]down- UniqueInternshipApplicationList
UniqueStatusList -[hidden]down- UniqueInternshipApplicationList

UniqueStatusList *-right-> "*" Status
UniqueInternshipApplicationList o-right-> InternshipApplication

InternshipApplication o-up-> "*" Status

InternshipApplication *--> Company
InternshipApplication *--> Role
InternshipApplication *--> Address
InternshipApplication *--> Phone
InternshipApplication *--> Email
InternshipApplication *--> ApplicationDate
InternshipApplication *--> Priority
@enduml
