@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

InternshipDiary *-right-> "1" UniqueInternshipApplicationList
InternshipDiary *-right-> "1" UniqueStatusList
UniqueStatusList -[hidden]down- UniqueInternshipApplicationList
UniqueStatusList -[hidden]down- UniqueInternshipApplicationList

UniqueStatusList *-right-> "*" Status
UniqueInternshipApplicationList o-right-> InternshipApplication

InternshipApplication o-up-> "1" Status

InternshipApplication *--> "1" Company
InternshipApplication *--> "1" Role
InternshipApplication *--> "0..1" Address
InternshipApplication *--> "0..1" Phone
InternshipApplication *--> "0..1" Email
InternshipApplication *--> "1" ApplicationDate
InternshipApplication *--> "1" Priority
InternshipApplication *--> "*" Interview
@enduml
