@startuml

hide circle
hide empty members
skinparam classAttributeIconSize 0

Class SortCommand {
}

Class SortCommandParser {
}

Interface Comparator <InternshipApplication> <<interface>>{
    + compare(InternshipApplication, InternshipApplication): int
    + toString(): String
    + reversed(): Comparator
}

Class XYZComparator {
}

Class ReversedComparator {
}

note as N1
  The Comparator interface is the default
  java.util.function.Comparator functional interface
end note

note as N2
    XYZComparator can be any of:
    ApplicationDateComparator, CompanyComparator, 
    PriorityComparator, RoleComparator,
    or StatusComparator.
end note

Comparator .. N1
XYZComparator .right. N2

SortCommandParser .left.> SortCommand : creates >
SortCommandParser .right.> XYZComparator
SortCommandParser ..> Comparator

SortCommand --> "1" Comparator

XYZComparator .down.|> Comparator
XYZComparator ..> ReversedComparator

ReversedComparator ..|> Comparator


@enduml
