@startuml

hide circle
hide empty members
skinparam classAttributeIconSize 0

Class FindCommandParser {

}

Class FindCommand {

}

Class Predicate <<interface>> {

}

Class XYZPredicate {

}

note as N1
  The Predicate interface is the default java.util.function.Predicate functional interface
end note

note as N2
                        XYZPredicate excludes ApplicationDateDuePredicate,
  InterviewDateDuePredicate, IsNotArchivedPredicate and StatusIsInterviewPredicate
end note

N1 .. Predicate
N2 .. XYZPredicate
FindCommandParser ...> XYZPredicate
FindCommandParser ...> Predicate
FindCommandParser ...> FindCommand
FindCommand ---> "*" Predicate
XYZPredicate ...|> Predicate

@enduml
