@startuml
start
:User executes command;

:Parse the command arguments to get an ArgumentMultimap ;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([preamble is given])
    :Add predicates for Company, Role, Address,
          Phone, Email, Priority and Status with
              the preamble keywords into a list;
    :Return a new FindCommand with isPreamble set to true;
else ([else])
    :Add all the required predicates with their
         corresponding keywords into a list;
    :Return a new FindCommand with isPreamble set to false;
endif
:Execute FindCommand;
stop
@enduml
