@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyInternshipDiary <<interface>>
Interface Model <<interface>>
Interface ObservableList <<interface>>
Class InternshipDiary
Class ReadOnlyInternshipDiary
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs <<interface>>

Package Statistics {
Class Statistics
}

Package InternshipApplication {
Class InternshipApplication
Class Address
Class Email
Class Role
Class Phone
Class Company
Class ApplicationDate
Class UniqueInternshipApplicationList
Class Priority
Package Interview {
Abstract Class Interview
}
}

Package Status {
Class Status <<enumeration>>
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

InternshipDiary .up.|> ReadOnlyInternshipDiary

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" InternshipDiary
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

InternshipDiary *--> "1" UniqueInternshipApplicationList
UniqueInternshipApplicationList o--> "*" InternshipApplication
InternshipApplication *--> "1" Company
InternshipApplication *--> "1" Role
InternshipApplication *--> "1" Address
InternshipApplication *--> "1" Phone
InternshipApplication *--> "1" Email
InternshipApplication *--> "1" ApplicationDate
InternshipApplication *--> "1" Priority
InternshipApplication *--> "*" Interview
InternshipApplication *-> "2" Status

Company -[hidden]right-> Role
Role -[hidden]right-> Address
Address -[hidden]right-> Phone
Phone -[hidden]right-> Email


ModelManager --> InternshipApplication
ModelManager -right-> "1" Statistics
@enduml
