@startuml

hide circle
hide empty members
skinparam classAttributeIconSize 0

Class ReminderCommand {

}

Class Predicate <<interface>> {

}

Class ApplicationDateDuePredicate {

}

Class StatusIsWishlistPredicate {

}

Class InterviewDateDuePredicate {

}

Class StatusIsInterviewPredicate {

}

Class IsNotArchivedPredicate {

}

Class ApplicationDateAndInterviewDateComparator {

}

note as N1
  The Predicate interface is the default java.util.function.Predicate functional interface
end note

note as N2
  The Comparator interface is the default java.util.Comparator functional interface
end note

N1 ... Predicate
N2 ... Comparator
ReminderCommand .down.> Predicate
ApplicationDateDuePredicate .up.|> Predicate
StatusIsWishlistPredicate ..up.|> Predicate
InterviewDateDuePredicate .up.|> Predicate
StatusIsInterviewPredicate ..up.|> Predicate
IsNotArchivedPredicate .up.|> Predicate
ReminderCommand .right.> Comparator

@enduml