@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":InternshipDiaryParser" as InternshipDiaryParser LOGIC_COLOR
participant "r:ReminderCommand" as ReminderCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
participant "c:ApplicationDateAndInterviewComparator" as ApplicationDateAndInterviewComparator LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("reminder")
activate LogicManager

LogicManager -> InternshipDiaryParser : parseCommand("reminder")
activate InternshipDiaryParser

create ReminderCommand
InternshipDiaryParser -> ReminderCommand
activate ReminderCommand

ReminderCommand --> InternshipDiaryParser : r
deactivate ReminderCommand

InternshipDiaryParser --> LogicManager : r
deactivate InternshipDiaryParser

LogicManager -> ReminderCommand : execute()
activate ReminderCommand

ReminderCommand -> Model : updateFilteredInternshipApplicationList(predicate)
activate Model

Model --> ReminderCommand
deactivate Model

create ApplicationDateAndInterviewComparator
ReminderCommand -> ApplicationDateAndInterviewComparator
activate ApplicationDateAndInterviewComparator

ApplicationDateAndInterviewComparator --> ReminderCommand : c
deactivate ApplicationDateAndInterviewComparator

ReminderCommand -> Model : updateFilteredInternshipApplicationList(c)
activate Model

Model --> ReminderCommand
deactivate Model

create CommandResult
ReminderCommand -> CommandResult
activate CommandResult

CommandResult --> ReminderCommand : result
deactivate CommandResult

ReminderCommand --> LogicManager : result
deactivate ReminderCommand

[<--LogicManager
deactivate LogicManager
@endumll
