@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR
skinparam linetype ortho


package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class ResultDisplay
Class CommandBox
Class EnteredCommandsHistory
package "Internship Application List" <<Rectangle>> {
Class InternshipApplicationListPanel
Class InternshipApplicationCard
}
package "Internship Application Detail" <<Rectangle>> {
Class InternshipApplicationDetail
Class InternshipApplicationDetailSetter
Class InterviewListPanel
Class InterviewCard
}
package "Display Footer" <<Rectangle>> {
Class StatisticsBarFooter
Class ComparatorDisplayFooter
Class PredicateDisplayFooter
Class StatusBarFooter
}
package "External Windows" <<Rectangle>> {
Class HelpWindow
Class StatisticsWindow
}
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> MainWindow
MainWindow -down-> StatisticsWindow
MainWindow *-right-> ComparatorDisplayFooter
MainWindow *-right-> StatisticsBarFooter
MainWindow -down-> HelpWindow
MainWindow *-down-> CommandBox
MainWindow *-down-> ResultDisplay
MainWindow *-down-> InternshipApplicationListPanel
MainWindow *-right-> StatusBarFooter
MainWindow *-right-> PredicateDisplayFooter
MainWindow *-down-> InternshipApplicationDetail
MainWindow *-down-> InternshipApplicationDetailSetter

InternshipApplicationDetail -down-> InterviewListPanel
InterviewListPanel -down-> InterviewCard

InternshipApplicationListPanel -down-> InternshipApplicationCard

MainWindow -down-|> UiPart

CommandBox -up-> EnteredCommandsHistory

ResultDisplay --|> UiPart
CommandBox --|> UiPart
InternshipApplicationListPanel --|> UiPart
InternshipApplicationCard --|> UiPart
StatusBarFooter --|> UiPart
StatisticsWindow --|> UiPart
StatisticsBarFooter--|> UiPart
ComparatorDisplayFooter --|> UiPart
PredicateDisplayFooter --|> UiPart
HelpWindow --|> UiPart
InternshipApplicationDetail --|> UiPart
InterviewListPanel --|> UiPart
InterviewCard --|> UiPart

InternshipApplicationDetailSetter ..> InternshipApplicationDetail

StatisticsBarFooter ..> Model
StatisticsWindow ..> Model
PredicateDisplayFooter ..> Model
ComparatorDisplayFooter ..> Model
InternshipApplicationCard ..> Model
InternshipApplicationDetail ..> Model
InterviewCard ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic


PredicateDisplayFooter -[hidden]up- ComparatorDisplayFooter
PredicateDisplayFooter -[hidden]left- StatisticsBarFooter

StatisticsBarFooter -[hidden]up- StatisticsWindow
StatisticsBarFooter -[hidden]left- InternshipApplicationListPanel
InternshipApplicationListPanel -[hidden]left- ResultDisplay

ResultDisplay -[hidden]up- HelpWindow
ResultDisplay -[hidden]left- StatusBarFooter

StatusBarFooter -[hidden]up- CommandBox

MainWindow -[hidden]-|> UiPart
@enduml
