= Foo Chi Fa - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:prURL: https://github.com/AY1920S2-CS2103T-F10-2/main/pull/

== PROJECT: Internship Diary

This portfolio provides an overview of my contributions to the Internship Diary project.

== Overview

**Internship Diary** is a command line interface (CLI) and desktop-based internship tracking application.

Arguably the most important phase in the journey of a computer science undergraduate is in their internship.
Internships are widely viewed as an entry point into the professional scene of computer science. Coupled with the
intense competition amongst highly desired internship companies, applying for internships become a tedious and stressful process. Numerous hours
would be spent planning, researching and organising internship applications.

As a group of computer science undergraduates, our team understands the anxiety and stress that internship
planning can cause. Therefore, we resolved ourselves to create a software that can ease the worries of fellow computer science
undergraduates when organising or tracking their internship applications.

Internship Diary is the culmination of this resolution, a simple yet elegant one-stop application for computer science
undergraduates' internship organising needs.

== Summary of contributions

* *Major enhancement*: implemented interview classes and commands
** **What it does:** This feature enables the user to add and modify interviews in an internship application, through the
interview commands.
** **Justification:** Interviews are important to an internship application. As interviews are almost always the next step
towards a successful application, it is important for the user to be able to organise and view his interviews.
Therefore, this features improves the product by allowing the user to add and modify interviews in an internship application.
** **Highlights:** This enhancement requires extensive testing as it makes massive increments to the current Model and Logic packages.
The implementation had to be constantly tweaked to ensure good integration with all other enhancements. Meticulousness and
the ability to write good test cases was integral to implementing this enhancement.

* *Major enhancement*: implemented display of internship application details in the Graphical User Interface (GUI)
** **What it does:** This feature enables the user to display the details of a selected internship application
(all the fields and list of interviews) on the right panel of the internship application.
** **Justification:** This feature improves the product as it allows the users to view all the details of the
internship application. This is important because the user will need to refer to the details in order to plan or
organise his internships.
** **Highlights:** This enhancement uses property change listeners to react to any changes by the user
to the displayed filtered list on the left panel and the internship application selected.
This implementation will allow for better flexibility in future modifications to internship application,
while being less prone to bugs and errors. Additionally, this enhancement requires strong knowledge of
javafx and the Ui structure of Internship Diary in order to produce a robust and well-integrated GUI enhancement.
** **Credits:** link:https://github.com/gerhean[Chan Ger Hean] for improving the implementation by using java property change.

* *Minor enhancement*: added select command to show Internship Application detail based on index.

* *Minor enhancement*: added parsers for new Internship Diary fields (status, priority, role).

* *Code contributed*: You can find all my code contributed here:
https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#=undefined&search=foochifa[RepoSense Report]

*Other contributions*:

* Project management:
** Set up Tags on Github Issues
** Created and managed Milestones on Github
** Managed meeting agendas and delegation of features, and translated them into issues on Github
** Assigned issues and PRs to relevant Milestones (from v1.1 to v2.0)
** Assigned relevant tags to issues

* Enhancement to existing features:
** Added additional test cases to improve coverage from 74% to 77% (Pull Request link:{PrURL}83[#83])
** Added builders to assist in tests (Pull Request link:{PrURL}64[#64], Pull Request link:{PrURL}83[#83])

* Documentation:
** Preliminary refactor of DG from AB3 to Internship Diary (Pull Request link:{PrURL}19[#19])
** Refactor UG to reflect v1.2 Internship Diary features (Pull Request link:{PrURL}83[#83])

* Community:
** Pull Requests reviewed (with non-trivial comments): link:{PrURL}31[#31], link:{PrURL}77[#77], link:{PrURL}134[#134]
, link:{PrURL}198[#198]

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=interviewStructure]

include::../UserGuide.adoc[tag=select]

include::../UserGuide.adoc[tag=interview]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=interview]
