= Ger Hean - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:prURL: https://github.com/AY1920S2-CS2103T-F10-2/main/pull/

== PROJECT: My Internship Diary

---

== Overview

Internship Diary is a desktop-based internship application tracking software. The user interacts with it using a CLI, and it has a GUI created with JavaFX.

The fact that the graduation requirements for Computer Science is at least 6 months of internship continuously haunts
the minds of every Computer Science student yet to complete this requirement. In order to aid in reducing the stress
of such students, we came up with the idea of the Internship Diary.

== Summary of contributions

* *Major enhancement*: Added *the ability to sort internship applications*.
(PR link:{prURL}71[#71], link:{prURL}113[#113], link:{prURL}199[#199])
** What it does: Sorts internship applications by field.
** Justification: This feature improves the product significantly as users can better manage their internship application list.
This is a basic feature which every organizer app need to have.

* *Minor enhancement*: Added a history command that allows the user to navigate to previous commands using up/down keys.
(PR link:{prURL}101[#101])
** Justification: Allows users to access similar past commands.
Also speeds up testing considerably.

* *Minor enhancement*: Added display of what the current list is sorted or filtered by.
(PR link:{prURL}114[#114]])

* *Minor enhancement*: Added DateTimeUtil to better parse dates.
(PR link:{prURL}104[#104])
** What it does: Allows application to parse date inputs formatted in different formats.
** Justification: Gives users more freedom as to how they want to enter dates.

* *Code contributed*:
https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#=undefined&search=gerhean[tP Code Dashboard]

* *Other contributions*:

** Project management:
*** Standardised the Intellij IDEA code formatter, in order to make the code base more uniform and to meet the checkstyle requirements (PR https://github.com/AY1920S2-CS2103T-F10-2/main/pull/221[#221]).

** Review/mentoring contributions:
*** Was the main technical adviser, and suggested implementation methods for several features.
(PR link:{prURL}82[#82], link:{prURL}118[#118], link:{prURL}216[#216])

** Enhancements to existing features:
*** Prettified the help window.
(PR link:{prURL}73[#73])
*** Allowed certain prefixes to be optional.
(PR link:{prURL}84[#84])
*** Added confirmation prompt for clear command.
(PR link:{prURL}98[#98])
*** Implemented Enums for Listener System.
(PR link:{prURL}125[#125])

** Helped with refactoring of Internship Diary from Address Book by updating the storage classes
(PR link:{prURL}33[#33], link:{prURL}50[#50])
and updating DG diagrams and text.

** Community:
*** Contributed to forum discussions (examples:
https://github.com/nus-cs2103-AY1920S2/forum/issues/74[1]
)

** Tools:
**** Set up Travis CI and Coveralls

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=sort]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=sort]
include::../DeveloperGuide.adoc[tag=clear]
include::../DeveloperGuide.adoc[tag=command-history]
