= Ger Hean - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: My Internship Diary

---

== Overview

Internship Diary is a desktop-based internship application tracking software.
The idea for this software came about when we realised that the nature of a computer science degree is internship-driven; in the sense that having the best possible internship experience during candidature will greatly improve your chance of landing a good job as a fresh graduate.
Essentially, your first big internship will serve as a pivotal moment for your future career.
Having said that, internship application is often a tedious and messy process, with companies having different hiring processes and requirements.
We set out to tackle this pain point -- by coming up with a solution to help computer science students manage and streamline their internship application journey Ultimately, we aim to make every student's internship hunt during their four years as a computer science undergraduate a pleasant one, and hopefully maximise their chances of landing the best possible internship.

== Summary of contributions

* *Major enhancement*: added *the ability to sort internship applications*.
** What it does: Sorts internship applications by field.
** Justification: This feature improves the product significantly as users can better manage their internship application list.

* *Minor enhancement*: added a history command that allows the user to navigate to previous commands using up/down keys.
* *Minor enhancement*: added display of what the current list is sorted or filtered by.

* *Code contributed*:
https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#=undefined&search=gerhean[tP Code Dashboard]

* *Other contributions*:

** Project management:
*** Created a Intellij IDEA code style XML (link) for the team to use, in order to standardise the code base and to
meet the checkstyle requirements.

** Review/mentoring contributions:
*** Was the main technical adviser, and suggested implementation methods for several features.
**** Examples:

** Enhancements to existing features:
*** Added confirmation prompt for clear command.
*** Prettified the help window.

** Documentation:

** Community:
*** Contributed to forum discussions (examples: https://github.com/nus-cs2103-AY1920S2/forum/issues/74[1])

** Tools:
**** Set up Travis CI and Coveralls

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=sort]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=sort]
include::../DeveloperGuide.adoc[tag=clear]
