= Internship Diary - Dev Ops
:site-section: DeveloperGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:warning-caption: :warning:
endif::[]
:repoURL: https://github.com/AY1920S2-CS2103T-F10-2/main

== Build Automation

Internship Diary uses https://gradle.org/[Gradle] for build automation.

See <<UsingGradle#, UsingGradle.adoc>> for more details.

== Continuous Integration

Internship Diary uses https://travis-ci.org/[Travis CI] for continuous integration.

See <<UsingTravis#, UsingTravis.adoc>> for more details.

== Coverage Reporting

Internship Diary uses https://coveralls.io/[Coveralls] to track code coverage.

See <<UsingCoveralls#, UsingCoveralls.adoc>> for more details.

== Automated Code Review

Internship Diary uses https://www.codacy.com//[Codacy] to automate code reviews.

== Managing Dependencies

Sometimes third-party libraries may be required (e.g. Jackson library for JSON parsing). You may include such dependencies into
the project using the 2 ways:

[loweralpha]
. Use Gradle to automatically manage the dependencies +
(Gradle can download the dependencies automatically)
. Manually download and include the libraries in the repository +
(Note that this will require extra work and may bloat the repo size)

== Making a Release

Here are the steps to create a new release.

.  Update the version number in link:{repoURL}/src/main/java/seedu/address/MainApp.java[`MainApp.java`].
.  Generate a JAR file <<UsingGradle#creating-the-jar-file, using Gradle>>.
.  Tag the repo with the appropriate version number. e.g. `v2.0`
.  https://help.github.com/articles/creating-releases/[Create a new release using GitHub] and upload the JAR file you created.

